name: SecretCreeper
version: '1.0-SNAPSHOT'
main: net.neological.secretCreeper.SecretCreeper
api-version: '1.21'
commands:
  start:
  addplayer:
  displayplayerlist:
  removeplayer:
  giveitems:
  changepresident:
    description: Manually change the president to a player with the given ID
    usage: /changepresident <player_id>
    permission: secretcreeper.admin
permissions:
  secretcreeper.admin:
    description: Allows admin commands for SecretCreeper.
    default: op